url: https://geekcruise.rocu.de
name: GeekCruise
title: GeekCruise
description: Geeks an Bord
copyright: Sebastian Schuster

baseurl: ""

remote_theme: shostakovich/zaunkoenig
plugins:
  - jekyll-feed
